@startuml
package "Kubernetes" {
  [Services]
  [Prometheus] --> POST1 
  POST1 --> [pushAppD] 
  [AppD Machine Agent]
}
 

node "AppD" {
  POST2 -> [APM ]
 } 

[AppD Machine Agent] --> [POST2] 

@enduml
